language: node_js

node_js:
  - "6"

services: mongodb

install:
  # Frontend
  - yarn install

  # Backend
  - cd backend
  - yarn install
  - cd ../

script:
  # Frontend
  - yarn run build-css
  - yarn run test -- --coverage
  - yarn run coveralls
  - yarn run build

  # Backend
  - cd backend
  - yarn run test
