sudo: required

language: node_js

node_js:
  - "6"

services:
  - mongodb
  - docker

before_install:
  # Setup AWS CLI
  - mkdir -p /tmp/aws-cli
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "/tmp/aws-cli/awscli-bundle.zip"
  - cd /tmp/aws-cli
  - unzip "awscli-bundle.zip"
  - ./awscli-bundle/install -b /tmp/aws-cli/aws
  - export PATH=/tmp/aws-cli:$PATH

install:
  # Frontend
  - cd $TRAVIS_BUILD_DIR
  - yarn install

  # Backend
  - cd backend
  - yarn install
  - cd ../

script:
  # Frontend
  - yarn run build-css
  - yarn run test -- --coverage
  - yarn run coveralls
  - yarn run build
  - aws s3 cp --recursive build/ s3://4dots-frontend/
  - aws configure set preview.cloudfront true
  # The goggles... they do nothing! https://www.youtube.com/watch?v=PWFF7ecArBk
  - "echo \"{ \\\"Paths\\\": { \\\"Quantity\\\": 1, \\\"Items\\\": [\\\"/index.html\\\"] }, \\\"CallerReference\\\": \\\"invalidate-index-$(date \"+%Y-%m-%d_%H_%M_%S\")\\\" }\" > invalidate-batch.json"
  - aws cloudfront create-invalidation --distribution-id E310QXY5ENUJKV --invalidation-batch file://invalidate-batch.json

  # Backend
  - cd backend
  - yarn run test
  - docker build -t 4dots .
  - /bin/sh -c '$(aws ecr get-login --no-include-email --region eu-west-2)'
  - docker tag 4dots:latest 247940857651.dkr.ecr.eu-west-2.amazonaws.com/4dots:latest
  - docker push 247940857651.dkr.ecr.eu-west-2.amazonaws.com/4dots:latest
