sudo: required

language: node_js

node_js:
  - "6"

services:
  - mongodb
  - docker

before_install:
  # Setup AWS CLI
  - mkdir -p /tmp/aws-cli
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "/tmp/aws-cli/awscli-bundle.zip"
  - cd /tmp/aws-cli
  - unzip "awscli-bundle.zip"
  - ./awscli-bundle/install -b /tmp/aws-cli/aws
  - export PATH=/tmp/aws-cli:$PATH

install:
  # Frontend
  - yarn install

  # Backend
  - cd backend
  - yarn install
  - cd ../

script:
  # Frontend
  - yarn run build-css
  - yarn run test -- --coverage
  - yarn run coveralls
  - yarn run build

  # Backend
  - cd backend
  - yarn run test
  - docker build -t 4dots .
  - /bin/sh -c $(aws ecr get-login --no-include-email --region eu-west-2)
  - docker tag 4dots:latest 247940857651.dkr.ecr.eu-west-2.amazonaws.com/4dots:latest
  - docker push 247940857651.dkr.ecr.eu-west-2.amazonaws.com/4dots:latest
